---
title: "Factors on Educational Achievement"
subtitle: "Olivia Abbott's Data Science Portfolio"
output:
  html_document:
    df_print: paged
---

## Abstract

The study I am working on is education. So far I have dowloaded data on educational achievement over time that give data on how much education people have achieved by county in the United States.  There are 4 categories of educational achievement: less than a high school diploma, high school diploma only, some college, and bachelor degree or higher. The data has been cleaned and some early visualizations have been created to help understand the data.

### 1. Discovery and Data Preparation

The first section of the project covers the data importation and cleaning, analysis, and visualizations to help me understand the data.

[Link](deliverable1.html) to phase 1 of the Portfolio. 


### 2. Model Planning and Building

The second section of the project brings in teacher salary data to test the relationship between student achievement and teacher salaries.

[Link](deliverable2.html) to phase 2 of the Portfolio.

### 3. Results and Operationalization

The last section of the project focuses on revising the previous sections of the project as well as creating some new models. It also sums up the project so far and expains some of the next steps for this project.

[Link](deliverable3.html) to phase 3 of the Portfolio.

